### PR TITLE
Read me update

### PR DESCRIPTION
**Pull request by ross-alex**
Content update for GIT LFS and "Creating the model data"

### CODE REVIEW

**Comment by ross-alex** [comment]
@HoldenJe I think I could have just merged this (with the purpose of also deleting branch). But, there was a message that this branch was 5 commits behind master - this makes sense because of changes to the read_tidy_export and shiny app. Tried to find a clear answer but only guessing - this pull/merge will only update the readMe changes into main, but not revert code changes where main is already ahead, right?

**Comment by HoldenJe** [comment]
You've got it - this branch is missing the commits that were just merged from the other two PRs. If there was more happening you could merge main in to this branch (see the main -> target-filtering PR I did earlier) to get all the recent commits in to this branch. If two branches edit the same file there is a possibility of creating a merge conflict. Those can be pretty easy to fix (once you've seen a few) but are definitely easier when only small changes have been made to files - thus, keeping active branches up to date is easier than dealing with one giant PR.

**Review by HoldenJe — APPROVED** [review]

**Comment by HoldenJe** [comment]
this would be another good PR to squash and merge since the individual commits are pretty trivial in nature. I'll leave it to you to complete.

**Comment by ross-alex** [comment]
ah, right - that would have been the place to squash. Next time. Thanks.

**Pull request merged**
